version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    assignees:
      - psachmann
    groups:
      microsoft:
        patterns:
          - Microsoft.*
      tunit:
        patterns:
          - TUnit.*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    assignees:
      - psachmann
