<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNetQuery.Extensions.DependencyInjection\DotNetQuery.Extensions.DependencyInjection.csproj" />
  </ItemGroup>
</Project>
