<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Mocks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNetQuery.Blazor\DotNetQuery.Blazor.csproj" />
    <ProjectReference Include="..\..\src\DotNetQuery.Blazor.DevTools\DotNetQuery.Blazor.DevTools.csproj" />
  </ItemGroup>
</Project>
