<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Reactive.Testing" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Mocks" />
    <PackageReference Include="TUnit.Mocks.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNetQuery.Core\DotNetQuery.Core.csproj" />
  </ItemGroup>
</Project>
