name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs.yaml'

jobs:
  docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Create docs
        run: dotnet docfx ./docs/docfx.json

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./docs/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
